config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  resources :posts
  resources :projects  
  resources :contacts, only: [:new, :create]
  resources :tags

  get "/pages/*page" => "pages#show"
  get 'welcome/index'
  root 'welcome#index'
 
  get '*path' => redirect('/')

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true 
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i 
  attribute :message,   :validate => true 
  attribute :nickname,  :captcha  => true 

  def headers 
  	{
  	  :subject => "Contact Form",
  	  :to => "anoopkanyan@gmail.com",
  	  :from => %("#{name}" <#{email}>)
    }
  end   

end	

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
 
  is_impressionable
  has_many :taggings
  has_many :tags, through: :taggings, dependent: :destroy

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    main: '300x200>'
  }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def tag_list
  	self.tags.collect do |tag|
     	tag.name
  	end.join(", ")
  end	

  def tag_list=(tags_string)
  	tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  	new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  	self.tags = new_or_found_tags
end

end
 

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :allow_iframe_requests

  private
    def allow_iframe_requests
      response.headers.delete('X-Frame-Options')
    end
  end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact =  Contact.new 
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render 'new'
    end   
  end  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  	@posts = Post.all.order("created_at desc")
  	@trending = @posts.sort_by {|post| post.impressionist_count}.reverse!
  	render template: "pages/#{params[:page]}"
  end	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]	
	before_action :authenticate_user!, except: [:index, :show]


	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)

		respond_to do |format|
          format.html
          format.rss { render :layout => false }
        end
	end
	
	def new
		@post = Post.new 
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Hellz yea, Anupsy! Your article was successfully saved."
		else
			render 'new', notice: "Oh no, Anupsy! I was unable to save your post."	
		end	
	end

	def show
		#impressionist(@post) 
	end	

	def edit
	end
	
	def update
		if @post.update post_params
			redirect_to @post, notice: "Huzza! Your article was successfully saved!" 
		else
			render 'edit'
		end
	end	

	def destroy
		@post.destroy
		redirect_to posts_path
	end



	private 

	def post_params
		params.require(:post).permit(:title, :content, :slug, :tag_list, :youtube_url, :image) 
	end 

	def find_post
		@post = Post.friendly.find(params[:id])
	end	
   

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]


	def index
		@projects = Project.all.order("created_at desc")
	end
	
	def new
		@project = Project.new
	end

	def create 
		@project = Project.new project_params

		if @project.save
			redirect_to @project, notice: "Nice! That project was successfully saved!"
		else
			render 'new'
		end		
	end	

	def show
	end

	def edit
	end
	
	def update
		if @project.update project_params
			redirect_to @project, notice: "Huzza! Your project was successfully updated!" 
		else
			render 'edit'
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end	
	
	def find_project
		@project = Project.friendly.find(params[:id])		
	end	

	private 

	def project_params
		params.require(:project).permit(:title, :description, :link, :slug, :image)
	end	
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  	@posts = @tag.posts.order("created_at desc").paginate(page: params[:page], per_page: 10)
  end	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
	@projects = Project.all.limit(3).order("created_at desc")
	@posts = Post.all.limit(25).order("created_at desc") 
  	@trending = @posts.sort_by {|post| post.impressionist_count}.reverse!
end	

end

app/helpers/application_helper.rb
module ApplicationHelper

	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code, language)
			Pygments.highlight(code, lexer:language)
		end
	end

	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: false)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true,	
		}

		Redcarpet::Markdown.new(renderer, options).render(content).html_safe

	end	

	def youtube_embed_post(youtube_url)
      if youtube_url[/youtu\.be\/([^\?]*)/]
        youtube_id = $1
      else
        # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
        youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
        youtube_id = $5
      end
      %Q{<iframe title="YouTube video player" id="post_youtube" src="https://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
    end



    def youtube_embed_main(youtube_url)
      if youtube_url[/youtu\.be\/([^\?]*)/]
        youtube_id = $1
      else
        # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
        youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
        youtube_id = $5
      end
      %Q{<iframe title="YouTube video player" width="100%" height="100%" src="https://www.youtube.com/embed/#{ youtube_id }?showinfo=0&controls=0&autohide=1" frameborder="0" allowfullscreen></iframe>}
    end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
  <h2> Thank You for your message!</h2>
  <p>We'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<% set_meta_tags title: 'Contact',
                 description: 'Get in touch with people at ChewTab',
                 keywords: 'contact, people, chewtab' ,
                 reverse: true %>

<h1 id="page_title">Say Hello!</h1>
		
		<div class="skinny_wrapper wrapper_padding">
			<%= form_for @contact do |f| %>
				<%= f.label :name %><br> 
				<%= f.text_field :name, required: true %>

				<br>

				<%= f.label :email %><br> 
				<%= f.email_field :email, required: true %>

				<br>

				<%= f.label :message %><br> 
				<%= f.text_area :message, as: :text %>

				<div class="hidden">
					<%= f.label :nickname %><br> 
				    <%= f.text_field :nickname, hint: 'leave this field blank' %>
				</div>	

				<%= f.submit 'Send Message', class: "button" %>	
			<% end %>

		</div>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-96927596-1', 'auto');
  ga('send', 'pageview');

</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= display_meta_tags %>
  <%= auto_discovery_link_tag :rss, posts_url(:format => :rss) %>

  <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet" async="async">
  <script src="https://use.fontawesome.com/a3c0a16723.js" async="async"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render :partial => 'layouts/google_analytics' %>
  <meta name="viewport" content="width=device-width, initial-scale=1" >
  <meta name="theme-color" content="#8bc6db" />
  <meta name="propeller" content="6bb4842f0d7a7c16549ccd5b29328cd9" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" async="async"></script>

  <meta name="msvalidate.01" content="24ED46A9DF59781A85814401D390E2A2" />
  <meta name="p:domain_verify" content="48cf9e04fb3b4febbdbbcfc13addcd67"/>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-2757163399431376",
          enable_page_level_ads: true
     });
</script>


<script async>(function(s,u,m,o,j,v){j=u.createElement(m);v=u.getElementsByTagName(m)[0];j.async=1;j.src=o;j.dataset.sumoSiteId='1db1b0acddc2f61cc60d658832ae9b734e44d9bf58374a7e026d64b729b9ad06';v.parentNode.insertBefore(j,v)})(window,document,'script','//load.sumo.com/');</script>


<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '177986376261020');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=177986376261020&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->


<script type="text/javascript">!function(t,e){"use strict";var r=function(t){try{var r=e.head||e.getElementsByTagName("head")[0],a=e.createElement("script");a.setAttribute("type","text/javascript"),a.setAttribute("src",t),r.appendChild(a)}catch(t){}};t.CollectId = "5aaf0f9c0873d442245a0173",r("https://s3.amazonaws.com/collectchat/launcher.js")}(window,document);</script>



</head>
<body>
<header id ="top_header" class="clearfix">
  <%= link_to "ChewTab", root_path, class:"name" %>
  <a href="#" class="menu"><i class="fa fa-bars"></i></a>
  <nav id="main_nav">
    <%= link_to "Stories", posts_path %>
    <%= link_to "Projects", projects_path %>
    <%= link_to "About", "/pages/about" %> 
    <%= link_to "Contact", new_contact_path %>
    <%= link_to "Disclosure", "/pages/disclosure" %>
    <%= link_to "Privacy", "/pages/privacy" %>
    <div id="social_icons_nav">
    <a href="https://www.facebook.com/ChewTab"><i class="fa fa-facebook" aria-hidden="true"></i></a>
    <a href="https://twitter.com/chewtab"><i class="fa fa-twitter" aria-hidden="true"></i></a>
    <!--  <a href=""><i class="fa fa-github" aria-hidden="true"></i></a> -->
    <a href="https://www.instagram.com/chewtab/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
    <a href="https://pinterest.com/brandchewtab/boards/"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> 
    <% end %>
    </div>
  </nav>
</header>

<% if notice %>
  <p class="notice"><%= notice %></p>
<% elsif alert %>  
  <p class="alert"><%= alert %></p>
<% end %>
<%= yield %>

<footer id="main_footer">  
      <p class="copyright">&copy; 2017 ChewTab
      </p>
     
      <nav>
        <a href="https://www.facebook.com/ChewTab"><i class="fa fa-facebook" aria-hidden="true"></i></a>
        <a href="https://twitter.com/chewtab"><i class="fa fa-twitter" aria-hidden="true"></i></a>
      <!--  <a href=""><i class="fa fa-github" aria-hidden="true"></i></a> -->
        <a href="https://www.instagram.com/chewtab/"><i class="fa fa-instagram" aria-hidden="true"></i></a>     
      </nav>
      <a href="//www.dmca.com/Protection/Status.aspx?ID=61317063-58d8-44a9-b538-319c8037afda" title="DMCA.com Protection Status" class="dmca-badge" style ="visibility: hidden;"> <img src="//images.dmca.com/Badges/dmca_protected_sml_120n.png?ID=61317063-58d8-44a9-b538-319c8037afda" alt="DMCA.com Protection Status"></a> <script src="//images.dmca.com/Badges/DMCABadgeHelper.min.js"> </script>
    </footer>   


</body>
</html>

app/views/pages/about.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
<div id="about_page" >
<p>ChewTab is an up and coming media company based out of <a href="https://en.wikipedia.org/wiki/Delhi">"saddi dilli"</a>. We keep ourselves open to opportunities and let us know if we can be of any help to you.</p>
<p>
For any queries, you can drop us a line <%= link_to "here", new_contact_path %>. We try our best to respond to all sorts of messages. 
</p>
</div>
</div>

app/views/pages/disclosure.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
<div id="about_page" >

	<h1><center> FTC Disclosure Statement </center></h1>
	<p>This site is monetized by affiliate program, which means the sites we link to in the posts will compensate us with a commission for purchases credited to this site.

	Some of the third party programs we use include Amazon.com, ClickBank, and others.

	The products which are recommended on this site are either products we use personally, or something we agree to endorse after researching it thoroughly. We recommend these products and services because we believe these products will help our readership in general. The statements made with regard to the products or services reflect our honest opinion based on the facts known at the time of writing.

	You should assume that a connection exists between chewtab.com and the providers of the referenced products and services, unless explicitly stated otherwise.
	</p>

</div>
</div>	

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>


var disqus_config = function () {
this.page.url = '<%= url_for([@post, {only_path:false}]) %>';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
this.page.title = '<%= @post.title %>'
};


(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://chewtab.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/posts/new.html.erb
<h1 id="page_title">New Post</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>  

app/views/posts/show.html.erb
<% set_meta_tags title: @post.title,
                 description: @post.content,
                 keywords: @post.tag_list.concat(',').concat(@post.title.parameterize(',')) , 
                 reverse: true,
                  og: {
  					title:    		@post.title,
  					type:     		'article',
  					url:      		request.original_url,
  					image:    	    @post.image.url(:original),
  					description: 	@post.content.truncate(157),
  					site_name:      "Chewtab" 	
				},
				
				 article: {
  						published_time:  @post.created_at 
  					},

  				 twitter: {
 					 card:  "photo",
  					 image: {
    				 	_:      @post.image.url(:main),
    				 	width:  300,
    					height: 200,
  						}
					}				
  				 	 %>


<div class="container">

<div class="LeftFloatAds"> <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Vertical Skyscrapers -->
<ins class="adsbygoogle"
     style="display:inline-block;width:120px;height:600px"
     data-ad-client="ca-pub-2757163399431376"
     data-ad-slot="6234393254"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script> </div>

<div id="post_show_content" class="skinny_wrapper wrapper_padding">

<!--			
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
-->
<!-- top_placement 
<ins class="adsbygoogle"
     style="display:block; margin-bottom: 1em;"
     data-ad-client="ca-pub-2757163399431376"
     data-ad-slot="4518166186"
     data-ad-format="auto"></ins>

   -->

			<header>
				<p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
			<h1><%= @post.title %></h1>
			<hr>
		  
		    </header>
		<div id="content">

		<!-- This is the thumbnail image, 
		not to be displayed here
		
		<p><%= image_tag @post.image.url %></p>
		-->
		
		<%= markdown @post.content %>
		<% if !(@post.youtube_url.blank?) %>
		<p><%= raw(youtube_embed_post(@post.youtube_url)) %></p>
		<% end %>


<!--
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block; text-align:center;"
     data-ad-layout="in-article"
     data-ad-format="fluid"
     data-ad-client="ca-pub-2757163399431376"
     data-ad-slot="9287115438"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		
DISABLED BECAUSE AUTO ADS ENABLED

-->



    <p class="tags">
  			TAGS:
  			<% @post.tags.each do |tag| %>
    			<%= link_to '#'.concat(tag.name), tag_path(tag) %> 
  			<% end %>
		</p>
		<!--
		<%= "#{@post.impressionist_count} views" %>
		-->
		</div>
		<hr>		
		<div id="share_box">
			<p>Share <%= @post.title %> </p>
			<a data-sumome-share-id="3a9c8497-62cb-45c0-9057-95a60fa4db99"></a>
			
			<!--
			<a href='http://trkur4.com/292520/32911?i=384786'><img src='http://pixxur.com/292520/384786-600x400.png' /></a>
			<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
			<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
			<a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
			-->
		</div>

		<% if user_signed_in? %>
		  	<div id="admin_links">
		  		<%= link_to "Edit Article", edit_post_path(@post)%>
		  		<%= link_to "Delete Artcile", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>
		  	</div>
		<% end %>
		<hr>


		<!-- Composite Start 
		
<div id="M260168ScriptRootC130877">
        <div id="M260168PreloadC130877">
        Loading...
    </div>
        <script>
                (function(){
            var D=new Date(),d=document,b='body',ce='createElement',ac='appendChild',st='style',ds='display',n='none',gi='getElementById';
            var i=d[ce]('iframe');i[st][ds]=n;d[gi]("M260168ScriptRootC130877")[ac](i);try{var iw=i.contentWindow.document;iw.open();iw.writeln("<ht"+"ml><bo"+"dy></bo"+"dy></ht"+"ml>");iw.close();var c=iw[b];}
            catch(e){var iw=d;var c=d[gi]("M260168ScriptRootC130877");}var dv=iw[ce]('div');dv.id="MG_ID";dv[st][ds]=n;dv.innerHTML=130877;c[ac](dv);
            var s=iw[ce]('script');s.async='async';s.defer='defer';s.charset='utf-8';s.src="//jsc.mgid.com/c/h/chewtab.com.130877.js?t="+D.getYear()+D.getMonth()+D.getDate()+D.getHours();c[ac](s);})();
    </script>
</div>
<!-- Composite End -->

				
<!--
		<script type="text/javascript">
  	var vglnk = { key: '5dd0aeb0a52057817111eb951d4cd889' };

  (function(d, t) {
    var s = d.createElement(t); s.type = 'text/javascript'; s.async = true;
    s.src = '//cdn.viglink.com/api/vglnk.js';
    var r = d.getElementsByTagName(t)[0]; r.parentNode.insertBefore(s, r);
  }(document, 'script'));
</script>
-->


<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="autorelaxed"
     data-ad-client="ca-pub-2757163399431376"
     data-ad-slot="7121025245"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>


<div class="fb-comments" data-href= <%= request.original_url%> data-width="100%" data-numposts="15"></div>


  

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.11&appId=301038950349786';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



<!-- top_placement 

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2757163399431376"
     data-ad-slot="4518166186"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

DISABLED BECAUSE AUTO ADS ENABLED
-->


</div>
<div class="RightFloatAds"> <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Vertical Skyscrapers -->
<ins class="adsbygoogle"
     style="display:inline-block;width:120px;height:600px"
     data-ad-client="ca-pub-2757163399431376"
     data-ad-slot="6234393254"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script> </div>

</div>

app/views/projects/edit.html.erb
 <h1 id="page_title">Edit Project</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/new.html.erb
<h1 id="page_title">New Project</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<% set_meta_tags title: @project.title,
                 description: @project.title,
                 keywords: @project.title.parameterize(',') , 
                 reverse: true %>

<div id="post_show_content" class="skinny_wrapper wrapper_padding">

<!-- top_placement 
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2757163399431376"
     data-ad-slot="4518166186"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


DISABLED BECAUSE AUTO ADS ENABLED
-->



			<header>
				<p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
			<h1><%= @project.title %></h1>
			<hr>
		    </header>
		<div id="content">
		
		<%= markdown @project.description %>

		<div class="button_wrapper">
		<a href="<%= @project.link %>" class="button" target="_blank"> Download <%= @project.title %></a>
		</div>

		<% if user_signed_in? %>
		  	<div id="admin_links">
		  		<%= link_to "Edit Project", edit_project_path(@project)%>
		  		<%= link_to "Delete Project", project_path(@project), method: :delete, data: { confirm: "Are you sure?"} %>
		  	</div>
		<% end %>

		</div>
		<hr>


<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="autorelaxed"
     data-ad-client="ca-pub-2757163399431376"
     data-ad-slot="7121025245"></ins>

<!--

		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block; text-align:center;"
     data-ad-layout="in-article"
     data-ad-format="fluid"
     data-ad-client="ca-pub-2757163399431376"
     data-ad-slot="9287115438"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>


DISABLED BECUASE AUTO ADS ENABLED
-->

</div>		